version: '3.10'

services:
  workbench-connector:
    image: "ndslabs/clowder-extractors-workbench"
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./downloads:/home/worksman
